import { RoutineItem } from '@/types'

export const nightRoutine: RoutineItem[] = [
  {
    id: 'night-sejjidul-istighfar',
    title: 'Sejjidul Istighfar — Zoteriu i Faljes',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: "Allahumma Anta Rabbi, la ilaha illa Anta, khalaqtani wa ana 'abduka, wa ana 'ala 'ahdika wa wa'dika mastata'tu. A'udhu bika min sharri ma sana'tu, abu'u laka bini'matika 'alayya, wa abu'u bidhanbi, faghfir li, fa innahu la yaghfirudh-dhunuba illa Anta.",
    translation: "O Allah, Ti je Zoti im, askush nuk meriton te adhurohet pervec Teje. Ti me krijove dhe une jam robi Yt, dhe qendroj ne besen dhe premtimin Tend sa te mundem. Kerkoj mbrojtje nga Ti prej te keqes qe kam bere. Pranoj mirsite e Tua ndaj meje, dhe pranoj mekatin tim, prandaj me fal, sepse askush nuk i fal mekatet pervec Teje.",
    source: 'Sahih al-Bukhari 6306',
    note: 'Kush e thote kete ne mbremje me besim te forte dhe vdes ate nate, do te jete nga banoret e Xhenetit.'
  },
  {
    id: 'night-dua-sleep-long',
    title: 'Duaja para gjumit — Sahih Muslim',
    arabic: 'اللَّهُمَّ إِنَّكَ خَلَقْتَ نَفْسِي وَأَنْتَ تَوَفَّاهَا لَكَ مَمَاتُهَا وَمَحْيَاهَا إِنْ أَحْيَيْتَهَا فَاحْفَظْهَا وَإِنْ أَمَتَّهَا فَاغْفِرْ لَهَا اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ',
    transliteration: "Allahumma innaka khalaqta nafsi wa Anta tawaffaha, laka mamatuha wa mahyaha. In ahyaytaha fahfadhha, wa in amattaha faghfir laha. Allahumma inni as'alukal-'afiyah.",
    translation: 'O Allah, Ti e krijove shpirtin tim dhe Ti e merr ate mbrapa. Ty i takon vdekja dhe jeta e tij. Nese i jep jete, mbroje; e nese e vdes, fale. O Allah, te kerkoj miresine.',
    source: 'Sahih Muslim 2712',
  },
  {
    id: 'night-dua-sleep',
    title: 'Duaja para gjumit — Sahih Bukhari',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismika Allahumma amutu wa ahya.',
    translation: 'Ne emrin Tend, o Allah, vdes dhe jetoj.',
    source: 'Sahih al-Bukhari 6324',
    note: 'Gjumi konsiderohet si "vdekje e vogel" ne Islam.'
  },
  {
    id: 'night-ayatul-kursi',
    title: 'Ajetul Kursi (2:255)',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    transliteration: "Allahu la ilaha illa Huwal-Hayyul-Qayyum. La ta'khudhuhuu sinatun wa la nawm. Lahu ma fis-samawati wa ma fil-ard. Man dhal-ladhi yashfa'u 'indahu illa bi-idhnih. Ya'lamu ma bayna aydihim wa ma khalfahum. Wa la yuhituna bishay'in min 'ilmihi illa bima sha'. Wasi'a kursiyyuhus-samawati wal-ard. Wa la ya'uduhu hifdhuhuma. Wa Huwal-'Aliyyul-'Adhim.",
    translation: 'Allahu! Nuk ka te adhuruar tjeter pervec Tij, te Perjeteshmit, Mbajtesit te gjithckajes. Nuk e kap As gjumi e as kotigja. E Tij eshte cdo gje qe eshte ne qiej dhe ne toke. Kush mund te nderhyje tek Ai pa lejen e Tij? Ai e di cfare ka perpara tyre dhe cfare do te kete pas tyre. Kursia e Tij shtrihet mbi qiejt dhe token, dhe ruajtja e tyre nuk e lodh Ate. Ai eshte me i Larti, me i Madhi.',
    source: 'Quran 2:255 — Sahih al-Bukhari 5010',
    note: 'Kush lexon Ajetul Kursin para gjumit, Allahu cakton nje engjell roje qe ta mbroje deri ne mengjes.'
  },
  {
    id: 'night-baqarah-last2',
    title: 'Dy ajetet e fundit te Sures Al-Bekare (2:285-286)',
    arabic: 'آمَنَ الرَّسُولُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِنْ رُسُلِهِ ۚ وَقَالُوا سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ ۝ لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِينَا أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِنْ قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ۖ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ۚ أَنْتَ مَوْلَانَا فَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
    transliteration: "Amanar-Rasulu bima unzila ilayhi mir-Rabbihi wal-mu'minun. Kullun amana billahi wa mala'ikatihi wa kutubihi wa rusulih. La nufarriqu bayna ahadin mir-rusulih. Wa qalu sami'na wa ata'na ghufranaka Rabbana wa ilaykal-masir. La yukallifullahu nafsan illa wus'aha. Laha ma kasabat wa 'alayha maktasabat. Rabbana la tu'akhidhna in nasina aw akhta'na. Rabbana wa la tahmil 'alayna isran kama hamaltahu 'alal-ladhina min qablina. Rabbana wa la tuhammilna ma la taqata lana bih. Wa'fu 'anna waghfir lana warhamna. Anta Mawlana fansurna 'alal-qawmil-kafirin.",
    translation: 'I Derguari besoi ne ate qe iu shpall nga Zoti i tij, si edhe besimtaret. Te gjithe besuan ne Allahun, engjejt, librat dhe te derguarit e Tij. Ne nuk bejme dallim midis asnje te derguari te Tij. Ata thane: Degjuam dhe u bindem. Faljen Tende, o Zoti yne, dhe tek Ti eshte kthimi. Allahu nuk e ngarkon askend mbi mundesite e tij. Per te eshte ajo qe fitoi, dhe kunder tij eshte ajo qe meritoi. Zoti yne, mos na denjo nese harrojme ose gabojme. Zoti yne, mos na ngarko me barre te rende sic i ngarkove ata para nesh. Zoti yne, mos na ngarko me ate qe nuk kemi fuqi ta mbajme. Na fal, na fal mekatet dhe na meshiro. Ti je Mbrojtesi yne, prandaj na ndihmo kunder popullit mohues.',
    source: 'Quran 2:285-286 — Sahih al-Bukhari 5009',
    note: 'Kush i lexon dy ajetet e fundit te Sures Al-Bekare naten, ato i mjaftojne atij.'
  },
  {
    id: 'night-ikhlas',
    title: 'Surja Al-Ihlas (112)',
    arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
    transliteration: 'Bismillahir-Rahmanir-Rahim. Qul Huwa Allahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.',
    translation: 'Ne emrin e Allahut, te Gjithemeshirshmit, Meshiruesit. Thuaj: Ai eshte Allahu, Nje i vetem. Allahu eshte Ai qe cdo gje ka nevoje per Te. Ai as ka lindur, e as eshte i lindur. Dhe askush nuk eshte i barabarte me Te.',
    source: 'Quran 112 — Sahih al-Bukhari 5017',
    note: 'Lexoje 3 here para gjumit, fryrji duarve dhe fshiji trupin.'
  },
  {
    id: 'night-falaq',
    title: 'Surja Al-Felek (113)',
    arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِنْ شَرِّ مَا خَلَقَ ۝ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    transliteration: "Bismillahir-Rahmanir-Rahim. Qul a'udhu bi Rabbil-falaq. Min sharri ma khalaq. Wa min sharri ghasiqin idha waqab. Wa min sharrin-naffathati fil-'uqad. Wa min sharri hasidin idha hasad.",
    translation: 'Ne emrin e Allahut, te Gjithemeshirshmit, Meshiruesit. Thuaj: Kerkoj mbrojtje te Zoti i agimit. Nga e keqja e asaj qe Ai krijoi. Dhe nga e keqja e erresires kur shtrihet. Dhe nga e keqja e atyre qe fryjne ne nyje. Dhe nga e keqja e smiruesit kur smiron.',
    source: 'Quran 113 — Sahih al-Bukhari 5017',
    note: 'Lexoje 3 here para gjumit, fryrji duarve dhe fshiji trupin.'
  },
  {
    id: 'night-nas',
    title: 'Surja An-Nas (114)',
    arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ',
    transliteration: "Bismillahir-Rahmanir-Rahim. Qul a'udhu bi Rabbin-nas. Malikin-nas. Ilahin-nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas.",
    translation: 'Ne emrin e Allahut, te Gjithemeshirshmit, Meshiruesit. Thuaj: Kerkoj mbrojtje te Zoti i njerezve. Sunduesi i njerezve. Zoti i njerezve. Nga e keqja e cytesit qe fshihet. Qe cyt ne gjokset e njerezve. Nga xhinet dhe njerezit.',
    source: 'Quran 114 — Sahih al-Bukhari 5017',
    note: 'Lexoje 3 here para gjumit, fryrji duarve dhe fshiji trupin.'
  },
  {
    id: 'night-mulk',
    title: 'Surja Al-Mulk (67) — Sundimi',
    arabic: '',
    transliteration: '',
    translation: 'Mbron nga denimi i varrit. Lexoje cdo nate para gjumit.',
    source: 'Quran 67:1-30 — Tirmidhi 2891',
    note: 'Ka nje sure ne Kuran me 30 ajete qe nderhyn per shokun e saj derisa ti falet.',
    ayahs: [
      { num: 1, arabic: 'تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ', transliteration: "Tabarakal-ladhi biyadihil-mulku wa Huwa 'ala kulli shay'in Qadir.", translation: 'I bekuar eshte Ai ne Doren e te Cilit eshte sundimi, dhe Ai eshte i Plotfuqishem mbi cdo gje.' },
      { num: 2, arabic: 'الَّذِي خَلَقَ الْمَوْتَ وَالْحَيَاةَ لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا ۚ وَهُوَ الْعَزِيزُ الْغَفُورُ', transliteration: "Alladhi khalaqal-mawta wal-hayata liyabluwakum ayyukum ahsanu 'amala, wa Huwal-'Azizul-Ghafur.", translation: 'Ai qe krijoi vdekjen dhe jeten per t\'ju provuar cili prej jush eshte me i miri ne vepra.' },
      { num: 3, arabic: 'الَّذِي خَلَقَ سَبْعَ سَمَاوَاتٍ طِبَاقًا ۖ مَا تَرَىٰ فِي خَلْقِ الرَّحْمَٰنِ مِنْ تَفَاوُتٍ ۖ فَارْجِعِ الْبَصَرَ هَلْ تَرَىٰ مِنْ فُطُورٍ', transliteration: "Alladhi khalaqa sab'a samawatin tibaqan, ma tara fi khalqir-Rahmani min tafawut, farji'il-basara hal tara min futur.", translation: 'Ai qe krijoi shtate qiej njerin mbi tjetrin. Nuk sheh ne krijimin e te Gjithemeshirshmit asnje mosperputhje.' },
      { num: 4, arabic: 'ثُمَّ ارْجِعِ الْبَصَرَ كَرَّتَيْنِ يَنْقَلِبْ إِلَيْكَ الْبَصَرُ خَاسِئًا وَهُوَ حَسِيرٌ', transliteration: "Thummarji'il-basara karratayn yanqalib ilaykal-basaru khasi'an wa huwa hasir.", translation: 'Pastaj ktheje shikimin dy here. Shikimi do te kthehet i perulur dhe i lodhur.' },
      { num: 5, arabic: 'وَلَقَدْ زَيَّنَّا السَّمَاءَ الدُّنْيَا بِمَصَابِيحَ وَجَعَلْنَاهَا رُجُومًا لِلشَّيَاطِينِ ۖ وَأَعْتَدْنَا لَهُمْ عَذَابَ السَّعِيرِ', transliteration: "Walaqad zayyanas-sama'ad-dunya bimasabiha wa ja'alnaha rujuman lish-shayatin, wa a'tadna lahum 'adhaba as-sa'ir.", translation: 'Ne e kemi zbukuruar qiellin me te afert me yje dhe i kemi bere ato si projektile kunder shejtaneve.' },
      { num: 6, arabic: 'وَلِلَّذِينَ كَفَرُوا بِرَبِّهِمْ عَذَابُ جَهَنَّمَ ۖ وَبِئْسَ الْمَصِيرُ', transliteration: "Walladhina kafaru birabbihim 'adhabu Jahannama wa bi'sal-masir.", translation: 'Dhe per ata qe mohuan Zotin e tyre eshte denimi i Xhehenemit, dhe sa perfundim i keq!' },
      { num: 7, arabic: 'إِذَا أُلْقُوا فِيهَا سَمِعُوا لَهَا شَهِيقًا وَهِيَ تَفُورُ', transliteration: "Idha ulqu fiha sami'u laha shahiqan wa hiya tafur.", translation: 'Kur hidhen ne te, degjojne nje frymemarrje te tmerrshme ndersa ai vlon.' },
      { num: 8, arabic: 'تَكَادُ تَمَيَّزُ مِنَ الْغَيْظِ ۖ كُلَّمَا أُلْقِيَ فِيهَا فَوْجٌ سَأَلَهُمْ خَزَنَتُهَا أَلَمْ يَأْتِكُمْ نَذِيرٌ', transliteration: "Takadu tamayyazu minal-ghayz, kullama ulqiya fiha fawjun sa'alahum khazanatuha alam ya'tikum nadhir.", translation: 'Gati shperthen nga terbimi. Sa here qe hidhet nje grup, rojet e tij i pyesin: A nuk ju erdhi paralajmerues?' },
      { num: 9, arabic: 'قَالُوا بَلَىٰ قَدْ جَاءَنَا نَذِيرٌ فَكَذَّبْنَا وَقُلْنَا مَا نَزَّلَ اللَّهُ مِنْ شَيْءٍ إِنْ أَنْتُمْ إِلَّا فِي ضَلَالٍ كَبِيرٍ', transliteration: "Qalu bala qad ja'ana nadhirun fakadh-dhabna wa qulna ma nazzalallahu min shay', in antum illa fi dalalin kabir.", translation: 'Ata thane: Po, na erdhi paralajmerues, por ne mohuam dhe thame: Allahu nuk ka zbritur asgje.' },
      { num: 10, arabic: 'وَقَالُوا لَوْ كُنَّا نَسْمَعُ أَوْ نَعْقِلُ مَا كُنَّا فِي أَصْحَابِ السَّعِيرِ', transliteration: "Waqalu law kunna nasma'u aw na'qilu ma kunna fi as-habis-sa'ir.", translation: 'Dhe thane: Sikur te kishim degjuar ose logjikuar, nuk do te ishim nga banoret e Zjarrit.' },
      { num: 11, arabic: 'فَاعْتَرَفُوا بِذَنْبِهِمْ فَسُحْقًا لِأَصْحَابِ السَّعِيرِ', transliteration: "Fa'tarafu bidhanbihim fa-suhqan li-as-habis-sa'ir.", translation: 'Dhe e pranuan mekatin e tyre, prandaj larg qofshin banoret e Zjarrit.' },
      { num: 12, arabic: 'إِنَّ الَّذِينَ يَخْشَوْنَ رَبَّهُمْ بِالْغَيْبِ لَهُمْ مَغْفِرَةٌ وَأَجْرٌ كَبِيرٌ', transliteration: 'Innal-ladhina yakhshawna Rabbahum bil-ghaybi lahum maghfiratun wa ajrun kabir.', translation: 'Vertet, ata qe i frikesohen Zotit te tyre ne fshehte, per ta ka falje dhe shperblim te madh.' },
      { num: 13, arabic: 'وَأَسِرُّوا قَوْلَكُمْ أَوِ اجْهَرُوا بِهِ ۖ إِنَّهُ عَلِيمٌ بِذَاتِ الصُّدُورِ', transliteration: "Wa asirru qawlakum awijharu bih, innahu 'Alimun bidhatis-sudur.", translation: 'Fshiheni fjalen tuaj ose shpalleni; Ai e di ate qe eshte ne gjokse.' },
      { num: 14, arabic: 'أَلَا يَعْلَمُ مَنْ خَلَقَ وَهُوَ اللَّطِيفُ الْخَبِيرُ', transliteration: "Ala ya'lamu man khalaq? Wa Huwal-Latiful-Khabir.", translation: 'A nuk e di Ai qe krijoi? Ai eshte i Buti, i Informuari.' },
      { num: 15, arabic: 'هُوَ الَّذِي جَعَلَ لَكُمُ الْأَرْضَ ذَلُولًا فَامْشُوا فِي مَنَاكِبِهَا وَكُلُوا مِنْ رِزْقِهِ ۖ وَإِلَيْهِ النُّشُورُ', transliteration: "Huwal-ladhi ja'ala lakumul-arda dhalulan famshuu fi manakibiha wa kulu mir rizqih, wa ilayhin-nushur.", translation: 'Eshte Ai qe e beri token te bute per ju, prandaj ecni neper shtigjet e saj dhe hani nga furnizimi i Tij.' },
      { num: 16, arabic: 'أَأَمِنْتُمْ مَنْ فِي السَّمَاءِ أَنْ يَخْسِفَ بِكُمُ الْأَرْضَ فَإِذَا هِيَ تَمُورُ', transliteration: "A-amintum man fis-sama'i an yakhsifa bikumul-arda fa-idha hiya tamur.", translation: 'A jeni te sigurt se Ai qe eshte ne qiell nuk do ta beje token t\'ju gellltite ndersa dridhej?' },
      { num: 17, arabic: 'أَمْ أَمِنْتُمْ مَنْ فِي السَّمَاءِ أَنْ يُرْسِلَ عَلَيْكُمْ حَاصِبًا ۖ فَسَتَعْلَمُونَ كَيْفَ نَذِيرِ', transliteration: "Am amintum man fis-sama'i an yursila 'alaykum hasiban, fasata'lamuna kayfa nadhir.", translation: 'Apo jeni te sigurt se Ai qe eshte ne qiell nuk do te dergoje mbi ju stuhi guresh?' },
      { num: 18, arabic: 'وَلَقَدْ كَذَّبَ الَّذِينَ مِنْ قَبْلِهِمْ فَكَيْفَ كَانَ نَكِيرِ', transliteration: 'Walaqad kadh-dhabal-ladhina min qablihim fakayfa kana nakir.', translation: 'Dhe vertet ata para tyre mohuan, e si ishte qortimi Im!' },
      { num: 19, arabic: 'أَوَلَمْ يَرَوْا إِلَى الطَّيْرِ فَوْقَهُمْ صَافَّاتٍ وَيَقْبِضْنَ ۚ مَا يُمْسِكُهُنَّ إِلَّا الرَّحْمَٰنُ ۚ إِنَّهُ بِكُلِّ شَيْءٍ بَصِيرٌ', transliteration: "Awalam yaraw ilat-tayri fawqahum saffatin wa yaqbidn, ma yumsikuhunna illar-Rahman, innahu bikulli shay'in Basir.", translation: 'A nuk i shohin zogjet siper tyre me krahe te hapura e te mbyllura? Askush nuk i mban ato pervec te Gjithemeshirshmit.' },
      { num: 20, arabic: 'أَمَّنْ هَٰذَا الَّذِي هُوَ جُنْدٌ لَكُمْ يَنْصُرُكُمْ مِنْ دُونِ الرَّحْمَٰنِ ۚ إِنِ الْكَافِرُونَ إِلَّا فِي غُرُورٍ', transliteration: 'Amman hadhal-ladhi huwa jundun lakum yansurakum min dunir-Rahman? Inil-kafirun illa fi ghurur.', translation: 'Kush eshte ai qe eshte ushtar per ju qe t\'ju ndihmoje pervec te Gjithemeshirshmit? Mohuesit jane vetem ne mashtrm.' },
      { num: 21, arabic: 'أَمَّنْ هَٰذَا الَّذِي يَرْزُقُكُمْ إِنْ أَمْسَكَ رِزْقَهُ ۚ بَلْ لَجُّوا فِي عُتُوٍّ وَنُفُورٍ', transliteration: "Amman hadhal-ladhi yarzuqukum in amsaka rizqah, bal lajju fi 'utuwwin wa nufur.", translation: 'Kush eshte ai qe do t\'ju furnizoje nese Ai ndalon furnizimin e Tij? Por ata vazhduan ne kryeneqesi dhe largim.' },
      { num: 22, arabic: 'أَفَمَنْ يَمْشِي مُكِبًّا عَلَىٰ وَجْهِهِ أَهْدَىٰ أَمَّنْ يَمْشِي سَوِيًّا عَلَىٰ صِرَاطٍ مُسْتَقِيمٍ', transliteration: "Afaman yamshi mukibban 'ala wajhihi ahda amman yamshi sawiyyan 'ala siratim mustaqim.", translation: 'A eshte me i udhezuar ai qe ecen i permbysur ne fytyren e tij, apo ai qe ecen drejt ne rrugen e drejte?' },
      { num: 23, arabic: 'قُلْ هُوَ الَّذِي أَنْشَأَكُمْ وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ ۖ قَلِيلًا مَا تَشْكُرُونَ', transliteration: "Qul Huwal-ladhi ansha'akum wa ja'ala lakumus-sam'a wal-absara wal-af'idah, qalilam ma tashkurun.", translation: 'Thuaj: Eshte Ai qe ju krijoi dhe ju dha degjimin, shikimin dhe zemrat; sa pak falenderoni!' },
      { num: 24, arabic: 'قُلْ هُوَ الَّذِي ذَرَأَكُمْ فِي الْأَرْضِ وَإِلَيْهِ تُحْشَرُونَ', transliteration: "Qul Huwal-ladhi dhara'akum fil-ardi wa ilayhi tuhsharun.", translation: 'Thuaj: Eshte Ai qe ju shumoi ne toke, dhe tek Ai do te mblidheni.' },
      { num: 25, arabic: 'وَيَقُولُونَ مَتَىٰ هَٰذَا الْوَعْدُ إِنْ كُنْتُمْ صَادِقِينَ', transliteration: "Wayaquluna mata hadhal-wa'du in kuntum sadiqin.", translation: 'Dhe thone: Kur eshte ky premtim, nese jeni te sinqerte?' },
      { num: 26, arabic: 'قُلْ إِنَّمَا الْعِلْمُ عِنْدَ اللَّهِ وَإِنَّمَا أَنَا نَذِيرٌ مُبِينٌ', transliteration: "Qul innamal-'ilmu 'indallahi wa innama ana nadhirun mubin.", translation: 'Thuaj: Dituria eshte vetem tek Allahu, dhe une jam vetem nje paralajmerues i qarte.' },
      { num: 27, arabic: 'فَلَمَّا رَأَوْهُ زُلْفَةً سِيئَتْ وُجُوهُ الَّذِينَ كَفَرُوا وَقِيلَ هَٰذَا الَّذِي كُنْتُمْ بِهِ تَدَّعُونَ', transliteration: "Falamma ra'awhu zulfatan si'at wujuhul-ladhina kafaru wa qila hadhal-ladhi kuntum bihi tadda'un.", translation: 'Por kur e shohin afer, fytyrat e mohuesve do te trembdhosen, dhe do t\'u thuhet: Kjo eshte ajo per te cilen thirisnit.' },
      { num: 28, arabic: 'قُلْ أَرَأَيْتُمْ إِنْ أَهْلَكَنِيَ اللَّهُ وَمَنْ مَعِيَ أَوْ رَحِمَنَا فَمَنْ يُجِيرُ الْكَافِرِينَ مِنْ عَذَابٍ أَلِيمٍ', transliteration: "Qul ara'aytum in ahlakaniyallahu wa man ma'iya aw rahimana, faman yujiru-kafirina min 'adhabin alim.", translation: 'Thuaj: Mendoni nese Allahu me vdes mua dhe ata me mua ose na meshiron, kush mund t\'i mbroje mohuesit nga denimi i dhembshem?' },
      { num: 29, arabic: 'قُلْ هُوَ الرَّحْمَٰنُ آمَنَّا بِهِ وَعَلَيْهِ تَوَكَّلْنَا ۖ فَسَتَعْلَمُونَ مَنْ هُوَ فِي ضَلَالٍ مُبِينٍ', transliteration: "Qul Huwar-Rahmanu amanna bihi wa 'alayhi tawakkalna, fasata'lamuna man huwa fi dalalin mubin.", translation: 'Thuaj: Ai eshte i Gjithemeshirshmi; ne besuam ne Te dhe Atij i besuam. Do ta kuptoni se kush eshte ne humbje te qarte.' },
      { num: 30, arabic: 'قُلْ أَرَأَيْتُمْ إِنْ أَصْبَحَ مَاؤُكُمْ غَوْرًا فَمَنْ يَأْتِيكُمْ بِمَاءٍ مَعِينٍ', transliteration: "Qul ara'aytum in asbaha ma'ukum ghawran faman ya'tikum bima'in ma'in.", translation: 'Thuaj: Mendoni nese uji juaj do te thahej, kush do t\'ju sjelle uje te rrjedhshem?' },
    ]
  },
  {
    id: 'night-sajdah',
    title: 'Surja As-Sexhde (32) — Sexhdja',
    arabic: '',
    transliteration: '',
    translation: 'Profeti ﷺ nuk flinte pa lexuar Suren As-Sexhde dhe Suren Al-Mulk.',
    source: 'Quran 32:1-30 — Tirmidhi 2892',
    note: 'Profeti ﷺ e lexonte cdo nate para gjumit se bashku me Suren Al-Mulk.',
    ayahs: [
      { num: 1, arabic: 'الم', transliteration: 'Alif-Lam-Mim.', translation: 'Elif-Lam-Mim.' },
      { num: 2, arabic: 'تَنْزِيلُ الْكِتَابِ لَا رَيْبَ فِيهِ مِنْ رَبِّ الْعَالَمِينَ', transliteration: "Tanzilul-Kitabi la rayba fihi mir-Rabbil-'alamin.", translation: 'Zbritja e Librit, per te cilen nuk ka dyshim, eshte nga Zoti i boteve.' },
      { num: 3, arabic: 'أَمْ يَقُولُونَ افْتَرَاهُ ۚ بَلْ هُوَ الْحَقُّ مِنْ رَبِّكَ لِتُنْذِرَ قَوْمًا مَا أَتَاهُمْ مِنْ نَذِيرٍ مِنْ قَبْلِكَ لَعَلَّهُمْ يَهْتَدُونَ', transliteration: "Am yaqulunaf-tarahu bal huwal-haqqu mir-Rabbika litundhira qawmam ma atahum min nadhirim min qablika la'allahum yahtadun.", translation: 'Apo thone se e trilloi? Jo, eshte e verteta nga Zoti yt, qe te paralajmerosh nje popull qe nuk u erdhi paralajmerues para teje.' },
      { num: 4, arabic: 'اللَّهُ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ وَمَا بَيْنَهُمَا فِي سِتَّةِ أَيَّامٍ ثُمَّ اسْتَوَىٰ عَلَى الْعَرْشِ', transliteration: "Allahul-ladhi khalaqas-samawati wal-arda wa ma baynahuma fi sittati ayyamin thummas-tawa 'alal-'Arsh.", translation: 'Eshte Allahu qe krijoi qiejt dhe token dhe cfare ka midis tyre ne gjashte dite, pastaj u ngrit mbi Arshin.' },
      { num: 5, arabic: 'يُدَبِّرُ الْأَمْرَ مِنَ السَّمَاءِ إِلَى الْأَرْضِ ثُمَّ يَعْرُجُ إِلَيْهِ فِي يَوْمٍ كَانَ مِقْدَارُهُ أَلْفَ سَنَةٍ مِمَّا تَعُدُّونَ', transliteration: "Yudabbirul-amra minas-sama'i ilal-ardi thumma ya'ruju ilayhi fi yawmin kana miqdaruhu alfa sanatin mimma ta'uddun.", translation: 'Ai drejton cdo ceshtje nga qielli ne toke, pastaj ngjitet tek Ai ne nje dite qe mat nje mije vjet sic i numroni ju.' },
      { num: 6, arabic: 'ذَٰلِكَ عَالِمُ الْغَيْبِ وَالشَّهَادَةِ الْعَزِيزُ الرَّحِيمُ', transliteration: "Dhalika 'Alimul-ghaybi wash-shahadatil-'Azizur-Rahim.", translation: 'Ky eshte Njohesi i te padukshmes dhe te dukshmes, i Plotfuqishmi, Meshiruesi.' },
      { num: 7, arabic: 'الَّذِي أَحْسَنَ كُلَّ شَيْءٍ خَلَقَهُ ۖ وَبَدَأَ خَلْقَ الْإِنْسَانِ مِنْ طِينٍ', transliteration: "Alladhi ahsana kulla shay'in khalaqahu wa bada'a khalqal-insani min tin.", translation: 'Ai qe e perfeksionoi cdo gje qe krijoi dhe e filloi krijimin e njeriut nga balta.' },
      { num: 8, arabic: 'ثُمَّ جَعَلَ نَسْلَهُ مِنْ سُلَالَةٍ مِنْ مَاءٍ مَهِينٍ', transliteration: "Thumma ja'ala naslahu min sulalatin min ma'in mahin.", translation: 'Pastaj e beri pasardhesine e tij nga nje pikeze uji te dobet.' },
      { num: 9, arabic: 'ثُمَّ سَوَّاهُ وَنَفَخَ فِيهِ مِنْ رُوحِهِ ۖ وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ ۚ قَلِيلًا مَا تَشْكُرُونَ', transliteration: "Thumma sawwahu wa nafakha fihi mir-ruhih, wa ja'ala lakumus-sam'a wal-absara wal-af'idah, qalilam ma tashkurun.", translation: 'Pastaj e formoi dhe i fryu nga shpirti i Tij dhe ju dha degjimin, shikimin dhe zemrat; sa pak falenderoni!' },
      { num: 10, arabic: 'وَقَالُوا أَإِذَا ضَلَلْنَا فِي الْأَرْضِ أَإِنَّا لَفِي خَلْقٍ جَدِيدٍ', transliteration: "Wa qalu a-idha dalalna fil-ardi a-inna lafi khalqin jadid.", translation: 'Dhe thane: Kur te humbim ne toke, a vertet do te jemi ne krijim te ri?' },
      { num: 11, arabic: 'قُلْ يَتَوَفَّاكُمْ مَلَكُ الْمَوْتِ الَّذِي وُكِّلَ بِكُمْ ثُمَّ إِلَىٰ رَبِّكُمْ تُرْجَعُونَ', transliteration: "Qul yatawaffakum malakul-mawtil-ladhi wukkila bikum thumma ila Rabbikum turja'un.", translation: 'Thuaj: Engjelli i vdekjes qe eshte caktuar per ju do t\'ju marre shpirtin, pastaj tek Zoti juaj do te ktheheni.' },
      { num: 12, arabic: 'وَلَوْ تَرَىٰ إِذِ الْمُجْرِمُونَ نَاكِسُو رُءُوسِهِمْ عِنْدَ رَبِّهِمْ', transliteration: "Wa law tara idhil-mujrimuna nakisu ru'usihim 'inda Rabbihim.", translation: 'Sikur te shihje kur kriminelet do te ulin kokat e tyre para Zotit te tyre.' },
      { num: 13, arabic: 'وَلَوْ شِئْنَا لَآتَيْنَا كُلَّ نَفْسٍ هُدَاهَا وَلَٰكِنْ حَقَّ الْقَوْلُ مِنِّي لَأَمْلَأَنَّ جَهَنَّمَ مِنَ الْجِنَّةِ وَالنَّاسِ أَجْمَعِينَ', transliteration: "Wa law shi'na la-atayna kulla nafsin hudaha wa lakin haqqal-qawlu minni la-amla'anna Jahannama minal-jinnati wan-nasi ajma'in.", translation: 'Dhe sikur te donim, do t\'i jepnim cdo shpirti udhezimin e tij, por u permbush fjala Ime: Do ta mbush Xhehenemin me xhine dhe njerez se bashku.' },
      { num: 14, arabic: 'فَذُوقُوا بِمَا نَسِيتُمْ لِقَاءَ يَوْمِكُمْ هَٰذَا إِنَّا نَسِينَاكُمْ', transliteration: "Fadhuqu bima nasitum liqa'a yawmikum hadha inna nasinakum.", translation: 'Prandaj shijoni per shkak se e harruat takimin e kesaj dite. Ne ju kemi harruar.' },
      { num: 15, arabic: 'إِنَّمَا يُؤْمِنُ بِآيَاتِنَا الَّذِينَ إِذَا ذُكِّرُوا بِهَا خَرُّوا سُجَّدًا وَسَبَّحُوا بِحَمْدِ رَبِّهِمْ وَهُمْ لَا يَسْتَكْبِرُونَ', transliteration: "Innama yu'minu bi-ayatinal-ladhina idha dukkiru biha kharru sujjadan wa sabbahu bihamdi Rabbihim wa hum la yastakbirun.", translation: 'Vetem ata besojne ne ajetet Tona qe kur perkujtohen me to, bien ne sexhde dhe lavderojne Zotin e tyre dhe nuk behen mendjemdhenja.' },
      { num: 16, arabic: 'تَتَجَافَىٰ جُنُوبُهُمْ عَنِ الْمَضَاجِعِ يَدْعُونَ رَبَّهُمْ خَوْفًا وَطَمَعًا وَمِمَّا رَزَقْنَاهُمْ يُنْفِقُونَ', transliteration: "Tatajafa junubuhum 'anil-madaji'i yad'una Rabbahum khawfan wa tama'an wa mimma razaqnahum yunfiqun.", translation: 'Anet e tyre largohen nga shtretrit, duke i lutur Zotit te tyre me frike dhe shprese, dhe shpenzojne nga ajo qe u kemi dhene.' },
      { num: 17, arabic: 'فَلَا تَعْلَمُ نَفْسٌ مَا أُخْفِيَ لَهُمْ مِنْ قُرَّةِ أَعْيُنٍ جَزَاءً بِمَا كَانُوا يَعْمَلُونَ', transliteration: "Fala ta'lamu nafsun ma ukhfiya lahum min qurrati a'yunin jaza'an bima kanu ya'malun.", translation: 'Askush nuk e di se cfare eshte fshehur per ta nga gezimi i syve, si shperblim per ate qe benin.' },
      { num: 18, arabic: 'أَفَمَنْ كَانَ مُؤْمِنًا كَمَنْ كَانَ فَاسِقًا ۚ لَا يَسْتَوُونَ', transliteration: "Afaman kana mu'minan kaman kana fasiqan la yastawun.", translation: 'A eshte ai qe eshte besimtar si ai qe eshte i pabinde? Nuk jane te barabarte.' },
      { num: 19, arabic: 'أَمَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ فَلَهُمْ جَنَّاتُ الْمَأْوَىٰ نُزُلًا بِمَا كَانُوا يَعْمَلُونَ', transliteration: "Ammal-ladhina amanu wa 'amilus-salihati falahum jannatul-ma'wa nuzulan bima kanu ya'malun.", translation: 'Per ata qe besuan dhe bene vepra te mira, per ta jane kopshtet e strehimit si mikpritje per ate qe benin.' },
      { num: 20, arabic: 'وَأَمَّا الَّذِينَ فَسَقُوا فَمَأْوَاهُمُ النَّارُ', transliteration: "Wa ammal-ladhina fasaqu fama'wahumun-nar.", translation: 'Per ata qe ishin te pabinde, streha e tyre eshte Zjarri.' },
      { num: 21, arabic: 'وَلَنُذِيقَنَّهُمْ مِنَ الْعَذَابِ الْأَدْنَىٰ دُونَ الْعَذَابِ الْأَكْبَرِ لَعَلَّهُمْ يَرْجِعُونَ', transliteration: "Wa lanudhi-qannahum minal-'adha-bil-adna dunal-'adha-bil-akbari la'allahum yarji'un.", translation: 'Dhe do t\'u bejme te shijojne denimin me te vogel para denimit me te madh, qe ndoshta kthehen.' },
      { num: 22, arabic: 'وَمَنْ أَظْلَمُ مِمَّنْ ذُكِّرَ بِآيَاتِ رَبِّهِ ثُمَّ أَعْرَضَ عَنْهَا', transliteration: "Wa man adhlamu mimman dukkira bi-ayati Rabbihi thumma a'rada 'anha.", translation: 'E kush eshte me i padrejte se ai qe perkujtohet me ajetet e Zotit e pastaj kthehet nga ato?' },
      { num: 23, arabic: 'وَلَقَدْ آتَيْنَا مُوسَى الْكِتَابَ فَلَا تَكُنْ فِي مِرْيَةٍ مِنْ لِقَائِهِ', transliteration: "Wa laqad atayna Musal-Kitaba fala takun fi miryatim mil-liqa'ih.", translation: 'Ne i dhame Musait Librin, prandaj mos dysho per takimin e Tij.' },
      { num: 24, arabic: 'وَجَعَلْنَا مِنْهُمْ أَئِمَّةً يَهْدُونَ بِأَمْرِنَا لَمَّا صَبَرُوا', transliteration: "Wa ja'alna minhum a'immatan yahduna bi-amrina lamma sabaru.", translation: 'Dhe beme prej tyre udheheqes qe udhezonin me urdherin Tone kur duruan.' },
      { num: 25, arabic: 'إِنَّ رَبَّكَ هُوَ يَفْصِلُ بَيْنَهُمْ يَوْمَ الْقِيَامَةِ فِيمَا كَانُوا فِيهِ يَخْتَلِفُونَ', transliteration: 'Inna Rabbaka Huwa yafsilu baynahum yawmal-Qiyamati fima kanu fihi yakhtalifun.', translation: 'Vertet Zoti yt do te gjykoje midis tyre ne Diten e Kijametit per ate qe nuk pajtoheshin.' },
      { num: 26, arabic: 'أَوَلَمْ يَهْدِ لَهُمْ كَمْ أَهْلَكْنَا مِنْ قَبْلِهِمْ مِنَ الْقُرُونِ يَمْشُونَ فِي مَسَاكِنِهِمْ', transliteration: 'Awalam yahdi lahum kam ahlakna min qablihim minal-quruni yamshuna fi masakinihim.', translation: 'A nuk u tregoi atyre sa breza kemi shkaterruar para tyre, ne banesat e te cileve ecin?' },
      { num: 27, arabic: 'أَوَلَمْ يَرَوْا أَنَّا نَسُوقُ الْمَاءَ إِلَى الْأَرْضِ الْجُرُزِ فَنُخْرِجُ بِهِ زَرْعًا تَأْكُلُ مِنْهُ أَنْعَامُهُمْ وَأَنْفُسُهُمْ', transliteration: "Awalam yaraw anna nasuqul-ma'a ilal-ardil-juruzi fanukhriju bihi zar'an ta'kulu minhu an'amuhum wa anfusuhum.", translation: 'A nuk shohin se Ne e drejtojme ujin ne token e thate e nxjerrim me te bime qe ushqehen kafshet e tyre dhe ata vete?' },
      { num: 28, arabic: 'وَيَقُولُونَ مَتَىٰ هَٰذَا الْفَتْحُ إِنْ كُنْتُمْ صَادِقِينَ', transliteration: "Wa yaquluna mata hadhal-fathu in kuntum sadiqin.", translation: 'Dhe thone: Kur eshte ky clirim, nese jeni te sinqerte?' },
      { num: 29, arabic: 'قُلْ يَوْمَ الْفَتْحِ لَا يَنْفَعُ الَّذِينَ كَفَرُوا إِيمَانُهُمْ وَلَا هُمْ يُنْظَرُونَ', transliteration: "Qul yawmal-fathi la yanfa'ul-ladhina kafaru imanuhum wa la hum yundharun.", translation: 'Thuaj: Ne Diten e Clirimit, nuk do t\'u beje dobi mohuesve besimi i tyre, e as do t\'u jepet afat.' },
      { num: 30, arabic: 'فَأَعْرِضْ عَنْهُمْ وَانْتَظِرْ إِنَّهُمْ مُنْتَظِرُونَ', transliteration: "Fa-a'rid 'anhum wantadhir innahum muntadhirun.", translation: 'Prandaj kthehu nga ata dhe prit; vertet ata jane duke pritur.' },
    ]
  },
  // ═══ SHENDET MENDOR ═══
  {
    id: 'night-mental-ankth',
    title: 'Lehtesim nga depresioni dhe ankthi',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ',
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazani, wa a'udhu bika minal-'ajzi wal-kasali, wa a'udhu bika minal-jubni wal-bukhli, wa a'udhu bika min ghalabatid-dayni wa qahrir-rijal.",
    translation: 'O Allah, kerkoj mbrojtje tek Ti nga brenga dhe pikellimi, nga pafuqishmeria dhe dembelizmi, nga frika dhe koprracia, dhe nga mbytja ne borxhe dhe shtypja e njerezve.',
    source: 'Sahih al-Bukhari 6369',
    note: 'Profeti ﷺ e thoshte kete dua shpesh. Mbulon cdo forme te stresit emocional.'
  },
  {
    id: 'night-mental-musa',
    title: 'Duaja e Profetit Musa — Kur je ne nevoje',
    arabic: 'رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ',
    transliteration: 'Rabbi inni lima anzalta ilayya min khayrin faqir.',
    translation: 'Zoti im, une kam nevoje per cfaredo te mire qe do te me dergosh.',
    source: 'Quran 28:24',
    note: 'Profeti Musa e tha kete kur ishte i huaj pa asgje — dhe Allahu iu pergjigj menjehere me strehim, familje dhe furnizim.'
  },
]

export const morningRoutine: RoutineItem[] = [
  {
    id: 'morning-dua-wakeup',
    title: 'Duaja kur zgjohesh',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: 'Alhamdu lillahil-ladhi ahyana ba\'da ma amatana wa ilayhin-nushur.',
    translation: 'Falenderimi i takon Allahut qe na dha jete pasi na kishte vdekur, dhe tek Ai eshte ringjallja.',
    source: 'Sahih al-Bukhari 6312',
    note: 'Fjala e pare qe duhet te thuash kur hap syte ne mengjes.'
  },
  {
    id: 'morning-fatiha',
    title: 'Surja Al-Fatiha (1)',
    arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nالْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ\nالرَّحْمَٰنِ الرَّحِيمِ\nمَالِكِ يَوْمِ الدِّينِ\nإِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ\nاهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ\nصِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
    transliteration: "Bismillahir-Rahmanir-Rahim. Alhamdu lillahi Rabbil-'alamin. Ar-Rahmanir-Rahim. Maliki yawmid-Din. Iyyaka na'budu wa iyyaka nasta'in. Ihdinas-siratal-mustaqim. Siratal-ladhina an'amta 'alayhim, ghayril-maghdubi 'alayhim wa lad-dallin.",
    translation: 'Ne emrin e Allahut, te Gjithemeshirshmit, Meshiruesit. Falenderimi i takon Allahut, Zotit te boteve. Te Gjithemeshirshmit, Meshiruesit. Sunduesit te Dites se Gjykimit. Vetem Ty te adhurojme dhe vetem nga Ti ndihme kerkojme. Na udheze ne rrugen e drejte. Rrugen e atyre qe i begatove, jo te atyre qe merituan zemerirnin, e as te atyre qe u humbem.',
    source: 'Quran 1:1-7 — Sahih al-Bukhari 4474',
    note: 'Sureja me e madhe ne Kuran. Nena e Librit.'
  },
  {
    id: 'morning-ayatul-kursi',
    title: 'Ajetul Kursi (2:255)',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    transliteration: "Allahu la ilaha illa Huwal-Hayyul-Qayyum. La ta'khudhuhuu sinatun wa la nawm. Lahu ma fis-samawati wa ma fil-ard. Man dhal-ladhi yashfa'u 'indahu illa bi-idhnih. Ya'lamu ma bayna aydihim wa ma khalfahum. Wa la yuhituna bishay'in min 'ilmihi illa bima sha'. Wasi'a kursiyyuhus-samawati wal-ard. Wa la ya'uduhu hifdhuhuma. Wa Huwal-'Aliyyul-'Adhim.",
    translation: 'Allahu! Nuk ka te adhuruar tjeter pervec Tij, te Perjeteshmit, Mbajtesit te gjithckajes. Nuk e kap As gjumi e as kotigja. E Tij eshte cdo gje qe eshte ne qiej dhe ne toke. Kush mund te nderhyje tek Ai pa lejen e Tij? Kursia e Tij shtrihet mbi qiejt dhe token. Ai eshte me i Larti, me i Madhi.',
    source: 'Quran 2:255 — al-Hakim (Sahih)',
    note: 'Kush lexon Ajetul Kursin ne mengjes do te mbrohet deri ne mbremje.'
  },
  {
    id: 'morning-ikhlas',
    title: 'Surja Al-Ihlas (112)',
    arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
    transliteration: 'Bismillahir-Rahmanir-Rahim. Qul Huwa Allahu Ahad. Allahus-Samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.',
    translation: 'Ne emrin e Allahut, te Gjithemeshirshmit, Meshiruesit. Thuaj: Ai eshte Allahu, Nje i vetem. Allahu eshte Ai qe cdo gje ka nevoje per Te. Ai as ka lindur, e as eshte i lindur. Dhe askush nuk eshte i barabarte me Te.',
    source: 'Quran 112 — Abu Dawud 5082',
    note: 'Lexoje 3 here ne mengjes per mbrojtje te plote.'
  },
  {
    id: 'morning-falaq',
    title: 'Surja Al-Felek (113)',
    arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِنْ شَرِّ مَا خَلَقَ ۝ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    transliteration: "Bismillahir-Rahmanir-Rahim. Qul a'udhu bi Rabbil-falaq. Min sharri ma khalaq. Wa min sharri ghasiqin idha waqab. Wa min sharrin-naffathati fil-'uqad. Wa min sharri hasidin idha hasad.",
    translation: 'Ne emrin e Allahut, te Gjithemeshirshmit, Meshiruesit. Thuaj: Kerkoj mbrojtje te Zoti i agimit. Nga e keqja e asaj qe Ai krijoi. Dhe nga e keqja e erresires kur shtrihet. Dhe nga e keqja e atyre qe fryjne ne nyje. Dhe nga e keqja e smiruesit kur smiron.',
    source: 'Quran 113 — Abu Dawud 5082',
    note: 'Lexoje 3 here ne mengjes per mbrojtje te plote.'
  },
  {
    id: 'morning-nas',
    title: 'Surja An-Nas (114)',
    arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ',
    transliteration: "Bismillahir-Rahmanir-Rahim. Qul a'udhu bi Rabbin-nas. Malikin-nas. Ilahin-nas. Min sharril-waswasil-khannas. Alladhi yuwaswisu fi sudurin-nas. Minal-jinnati wan-nas.",
    translation: 'Ne emrin e Allahut, te Gjithemeshirshmit, Meshiruesit. Thuaj: Kerkoj mbrojtje te Zoti i njerezve. Sunduesi i njerezve. Zoti i njerezve. Nga e keqja e cytesit qe fshihet. Qe cyt ne gjokset e njerezve. Nga xhinet dhe njerezit.',
    source: 'Quran 114 — Abu Dawud 5082',
    note: 'Lexoje 3 here ne mengjes per mbrojtje te plote.'
  },
  {
    id: 'morning-imran',
    title: 'Ajetet e fundit te Sures Al-Imran (3:190-194)',
    arabic: '',
    transliteration: '',
    translation: 'Profeti ﷺ i lexonte keto ajete kur zgjohej naten.',
    source: 'Quran 3:190-194 — Sahih al-Bukhari 4569',
    note: 'Profeti ﷺ lexonte ajetet e fundit te Sures Al-Imran kur zgjohej naten.',
    ayahs: [
      { num: 190, arabic: 'إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ لِأُولِي الْأَلْبَابِ', transliteration: "Inna fi khalqis-samawati wal-ardi wakhtilafil-layli wan-nahari la-ayatil-li-ulil-albab.", translation: 'Vertet, ne krijimin e qiejve dhe te tokes dhe ne ndryshimin e nates e te dites ka shenja per ata qe kane mendje.' },
      { num: 191, arabic: 'الَّذِينَ يَذْكُرُونَ اللَّهَ قِيَامًا وَقُعُودًا وَعَلَىٰ جُنُوبِهِمْ وَيَتَفَكَّرُونَ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ رَبَّنَا مَا خَلَقْتَ هَٰذَا بَاطِلًا سُبْحَانَكَ فَقِنَا عَذَابَ النَّارِ', transliteration: "Alladhina yadhkurunallaha qiyaman wa qu'udan wa 'ala junubihim wa yatafakkaruna fi khalqis-samawati wal-ard. Rabbana ma khalaqta hadha batilan subhanaka faqina 'adhaban-nar.", translation: 'Ata qe e perkujtojne Allahun duke qendruar ne kembe, ulur dhe shtrire, dhe mendojne per krijimin e qiejve e te tokes: Zoti yne, nuk e krijove kete kot; i lavdishem qofsh; na ruaj nga denimi i Zjarrit.' },
      { num: 192, arabic: 'رَبَّنَا إِنَّكَ مَنْ تُدْخِلِ النَّارَ فَقَدْ أَخْزَيْتَهُ ۖ وَمَا لِلظَّالِمِينَ مِنْ أَنْصَارٍ', transliteration: "Rabbana innaka man tudkhilin-nara faqad akhzaytah, wa ma lidh-dhalimina min ansar.", translation: 'Zoti yne, ate qe e fut ne Zjarr e ke turperuar, dhe per te padrejtet nuk ka ndihmues.' },
      { num: 193, arabic: 'رَبَّنَا إِنَّنَا سَمِعْنَا مُنَادِيًا يُنَادِي لِلْإِيمَانِ أَنْ آمِنُوا بِرَبِّكُمْ فَآمَنَّا ۚ رَبَّنَا فَاغْفِرْ لَنَا ذُنُوبَنَا وَكَفِّرْ عَنَّا سَيِّئَاتِنَا وَتَوَفَّنَا مَعَ الْأَبْرَارِ', transliteration: "Rabbana innana sami'na munadiyan yunadi lil-imani an aminu bi Rabbikum fa-amanna. Rabbana faghfir lana dhunubana wa kaffir 'anna sayyi'atina wa tawaffana ma'al-abrar.", translation: 'Zoti yne, ne degjuam nje thirrjes qe thirtje per besim: Besoni ne Zotin tuaj, dhe ne besuam. Zoti yne, na fal mekatet, na largo te keqijat dhe na vdis me te miret.' },
      { num: 194, arabic: 'رَبَّنَا وَآتِنَا مَا وَعَدْتَنَا عَلَىٰ رُسُلِكَ وَلَا تُخْزِنَا يَوْمَ الْقِيَامَةِ ۗ إِنَّكَ لَا تُخْلِفُ الْمِيعَادَ', transliteration: "Rabbana wa atina ma wa'adtana 'ala rusulika wa la tukhzina yawmal-qiyamah. Innaka la tukhliful-mi'ad.", translation: 'Zoti yne, na jep ate qe na premtove permes te derguarve Tu dhe mos na turpero ne Diten e Kijametit. Vertet Ti nuk e then premtimin.' },
    ]
  },
  // ═══ PASURIA & RIZKU ═══
  {
    id: 'morning-rizq-hallall',
    title: 'Duaja per furnizim hallall',
    arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
    transliteration: "Allahummakfini bihalalika 'an haramika, wa aghnini bifadlika 'amman siwak.",
    translation: 'O Allah, me mjafto me ate qe ke lejuar qe te mos kem nevoje per ate qe ke ndaluar, dhe me bej te pasur me bujarine Tende qe te mos kerkoj nga askush tjeter pervec Teje.',
    source: "Jami' at-Tirmidhi 3563",
    note: 'E mesoi Profeti ﷺ Aliun kur ishte ne borxh.'
  },
  {
    id: 'morning-rizq-udhezim',
    title: 'Duaja per udhezim dhe pavaresine',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَىٰ وَالتُّقَىٰ وَالْعَفَافَ وَالْغِنَىٰ',
    transliteration: "Allahumma inni as'alukal-huda wat-tuqa wal-'afafa wal-ghina.",
    translation: 'O Allah, te kerkoj udhezim, devotshmeri, nder dhe pavaresine.',
    source: 'Sahih Muslim 2721',
  },
  {
    id: 'morning-rizq-besim',
    title: 'Besimi ne planin e Allahut',
    arabic: 'وَمَا تَوْفِيقِي إِلَّا بِاللَّهِ ۚ عَلَيْهِ تَوَكَّلْتُ وَإِلَيْهِ أُنِيبُ',
    transliteration: "Wa ma tawfiqi illa billahi 'alayhi tawakkaltu wa ilayhi unib.",
    translation: 'Suksesi im nuk eshte pervec nga Allahu. Atij i jam besuar dhe tek Ai kthehem.',
    source: 'Quran 11:88',
    note: 'Fjalet e Profetit Shuajb, qe na kujtojne se cdo sukses vjen nga Allahu.'
  },
]
